development:
  sessions:
    default:
      database: iq_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: iq_test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
<% if ENV['MONGOHQ_URL'] %>
  <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  sessions:
    default:
      database: <%= uri.path.sub('/', '') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
  options:
    use_utc: true
<% end %>